# Generated by Django 5.0.5 on 2024-11-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_quantity_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(default=0, null=True, verbose_name='Минимальное количество'),
        ),
    ]
