# Generated by Django 5.0.5 on 2024-12-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_description_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Штрихкод'),
        ),
    ]
