# Generated by Django 5.0.5 on 2024-12-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_shop_about_shop_contacts_shop_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(default=0, verbose_name='Минимальный остаток'),
        ),
    ]
