# Generated by Django 5.1.2 on 2024-11-17 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expend_type', models.CharField(choices=[('rent', 'Аренда'), ('utilities', 'Коммунальные услуги'), ('salaries', 'Зарплаты'), ('supplies', 'Поставки'), ('other', 'Другое')], max_length=50, verbose_name='Тип расхода')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(verbose_name='С даты')),
                ('end_date', models.DateField(verbose_name='По дату')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('paid', 'Оплачен'), ('unpaid', 'Не оплачен')], default='unpaid', max_length=10, verbose_name='Статус')),
                ('is_salary_confirmed', models.BooleanField(default=False, null=True, verbose_name='Подтверждение зарплаты')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shop', verbose_name='Магазин')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
