# Generated by Django 5.1.2 on 2024-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_date_expense_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('rent', 'Аренда'), ('utilities', 'Коммунальные услуги'), ('salaries', 'Зарплаты'), ('other', 'Другое')], max_length=50, verbose_name='Тип расхода'),
        ),
    ]
