# Generated by Django 5.0.5 on 2024-12-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomehistory',
            old_name='price_at_income',
            new_name='price_at_moment',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='soldhistory',
            name='updated',
        ),
        migrations.AddField(
            model_name='incomehistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='history.orderhistory'),
        ),
        migrations.AlterField(
            model_name='soldhistory',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='soldhistory',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
