# Generated by Django 5.1.2 on 2024-11-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldhistory',
            old_name='price_at_sale',
            new_name='price',
        ),
    ]
