# Generated by Django 5.0.5 on 2024-12-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_price_at_income_incomehistory_price_at_moment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldhistory',
            old_name='price_at_sale',
            new_name='price_at_moment',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('income', 'Поступление')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
