# Generated by Django 5.1.2 on 2024-12-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_soldhistory_price_at_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldhistory',
            name='price_at_moment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
