# Generated by Django 5.1.2 on 2024-11-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_price_at_sale_soldhistory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldhistory',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
