# Generated by Django 5.1.2 on 2024-11-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_remove_orderhistory_updated_remove_soldhistory_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomehistory',
            old_name='price_at_income',
            new_name='price',
        ),
    ]
