# Generated by Django 5.0.5 on 2024-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_rename_price_at_income_incomehistory_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomehistory',
            old_name='price',
            new_name='price_at_income',
        ),
        migrations.AddField(
            model_name='soldhistory',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='change',
            field=models.FloatField(null=True),
        ),
    ]
