# Generated by Django 5.0.5 on 2024-11-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_rename_price_incomehistory_price_at_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomehistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='history.orderhistory'),
        ),
    ]
