# Generated by Django 5.0.5 on 2024-11-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_incomehistory_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomehistory',
            old_name='price_at_income',
            new_name='price_at_moment',
        ),
        migrations.RenameField(
            model_name='soldhistory',
            old_name='price_at_sale',
            new_name='price_at_moment',
        ),
        migrations.AlterField(
            model_name='soldhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
