# Generated by Django 5.0.5 on 2024-11-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_orderhistory_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
